### ISSUE TITLE
Update to Node.js 0.12.9 at a minimum

### ISSUE THREAD

**Issue by tbroyer** [ozwillo/ozwillo-site#13]
See https://nodejs.org/en/blog/vulnerability/december-2015-security-releases/

(for such a new project, Node.js 5.x would probably be a better start than the oldish 0.12.x  though)

**Comment by bobeal** [comment]
It is already on 0.12.9 on the production platform (it is only my local installation that is outdated, I gonna update the README.md).

And +1 for upgrading to Node.js 5x but there had some (minor) compatibility doubts with Express as mentioned for instance in https://github.com/strongloop/express/issues/2754. But I'll try to do an upgrade quickly (as it is a very simple application, the risks are very very minor ...).
