### ISSUE TITLE
Fixes on projects page

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-site#6]
* The block « Les premières applications proposées » misses a grey background
* Event if not in the mockups, the first Occiware block should have a non-white background in order to be distinguished from the Deliverables blocks above it
* Delivered -> Deliverables ?
* Some titles (in French and English versions) miss spaces between words (like in attached screenshot)

![screen shot 2015-12-11 at 11 39 09](https://cloud.githubusercontent.com/assets/175382/11741857/eed6ab98-9ffb-11e5-9b05-ee78272f7b46.png)

**Comment by MLE-Astek** [comment]
[Fix](https://github.com/ozwillo/ozwillo-site/commit/349d87a7dae3c916a32f2e13b896b8ef34d6497b)
