### ISSUE TITLE
Fixes on contact page

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-site#7]
* Asterix ? the Gallic ? :-)
* Even if not in the mockups, subject is a mandatory field in the contact form
* The form layout is different from what is in the mockups (see screenshot)
* Local contacts are missing
* I don't see the icons next to address, phone and email (see screenshot)

![screen shot 2015-12-11 at 11 47 49](https://cloud.githubusercontent.com/assets/175382/11742029/1b0a81de-9ffd-11e5-872b-fbada0d8308a.png)

![screen shot 2015-12-11 at 11 50 35](https://cloud.githubusercontent.com/assets/175382/11742108/9c0e0756-9ffd-11e5-9043-bedaedd3dfce.png)

**Comment by MLE-Astek** [comment]
[Fix](https://github.com/ozwillo/ozwillo-site/commit/c3ac2c7a06450eb67dbc7d2f8fd9573557847d98)
